export const BGIS_2026_PARTICIPANTS = [
  {
    team: "EvoX Esports",
    phase: "Quarter Finals",
    placement: 1,
    seed: "Qualifier",
    roster: [
      { name: "Kaalan", country: "India" },
      { name: "Evil", country: "India" },
      { name: "ShaDow", country: "India" },
      { name: "SpyOp", country: "India" },
      { name: "Tonyy", country: "India" },
    ],
  },
  {
    team: "Team SouL",
    phase: "Quarter Finals",
    placement: 2,
    seed: "Qualifier",
    badges: ["Main", "Staff"],
    roster: [
      { name: "NakuL", country: "India", captain: true },
      { name: "Goblin", country: "India" },
      { name: "LEGIT", country: "India" },
      { name: "Jokerr", country: "India" },
      { name: "Thunder", country: "India" },
    ],
  },
  {
    team: "Meta Ninza",
    phase: "Quarter Finals",
    placement: 3,
    seed: "Qualifier",
    badges: ["Main", "Staff"],
    roster: [
      { name: "Shadow7", country: "India", captain: true },
      { name: "Fierce", country: "India" },
      { name: "Apollo", country: "India" },
      { name: "WhiteTiger", country: "India" },
      { name: "Javin", country: "India" },
    ],
  },
  {
    team: "Orangutan",
    phase: "Quarter Finals",
    placement: 4,
    seed: "Qualifier",
    badges: ["Main", "Staff"],
    roster: [
      { name: "AK", country: "India" },
      { name: "Aaru", country: "India", captain: true },
      { name: "Attanki", country: "India" },
      { name: "WizzGOD", country: "India" },
    ],
  },
  {
    team: "4Wolf x DoD",
    phase: "Quarter Finals",
    placement: 5,
    seed: "Qualifier",
    roster: [
      { name: "IMMORTAL", country: "India" },
      { name: "AVNISHOP", country: "India" },
      { name: "BHAALU", country: "India", captain: true },
      { name: "NooB", country: "India" },
      { name: "PIXIEOP", country: "India" },
    ],
  },
  {
    team: "Madkings Esports",
    phase: "Quarter Finals",
    placement: 6,
    seed: "Qualifier",
    roster: [
      { name: "SHADOW", country: "India", captain: true },
      { name: "ClutchGod", country: "India" },
      { name: "Syrax", country: "India" },
      { name: "PRO", country: "India" },
    ],
  },
  {
    team: "Sinewy Esports",
    phase: "Quarter Finals",
    placement: 7,
    seed: "Qualifier",
    roster: [
      { name: "Moksh", country: "India", captain: true },
      { name: "Vishu99", country: "India" },
      { name: "Ninjuu", country: "India" },
      { name: "Rexboy", country: "India" },
      { name: "NinjA", country: "India" },
    ],
  },
  {
    team: "Genesis Esports",
    phase: "Quarter Finals",
    placement: 8,
    seed: "Qualifier",
    roster: [
      { name: "ViPER", country: "India" },
      { name: "GravityJOD", country: "India", captain: true },
      { name: "HunterZ", country: "India" },
      { name: "FurY", country: "India" },
      { name: "Zap", country: "India" },
    ],
  },
  {
    team: "Team Tamilas",
    phase: "Quarter Finals",
    placement: 9,
    seed: "Qualifier",
    roster: [
      { name: "AIMGOD", country: "India" },
      { name: "FoxOP", country: "India" },
      { name: "MrIGL", country: "India", captain: true },
      { name: "Reaper", country: "India" },
    ],
  },
  {
    team: "Troy Tamilans",
    phase: "Quarter Finals",
    placement: 10,
    seed: "Qualifier",
    roster: [
      { name: "Auxin", country: "India" },
      { name: "Ayden", country: "India" },
      { name: "Lens77", country: "India" },
      { name: "Hesperos", country: "India" },
      { name: "Jazzy", country: "India" },
    ],
  },
  {
    team: "Vasista Esports",
    phase: "Quarter Finals",
    placement: 11,
    seed: "Qualifier",
    roster: [
      { name: "Beast", country: "India" },
      { name: "FusionOP", country: "India" },
      { name: "Hector", country: "India", captain: true },
      { name: "Saumay", country: "India" },
      { name: "Shayaan", country: "India" },
    ],
  },
  {
    team: "GodLike Esports",
    phase: "Quarter Finals",
    placement: 12,
    seed: "Qualifier",
    badges: ["Main", "Staff"],
    roster: [
      { name: "Spower", country: "India" },
      { name: "ADMINO", country: "India" },
      { name: "Godz", country: "India" },
      { name: "JONATHAN", country: "India" },
      { name: "Manya", country: "India", captain: true },
    ],
  },
  {
    team: "Wyld Fangs",
    phase: "Quarter Finals",
    placement: 13,
    seed: "Qualifier",
    roster: [
      { name: "SPRAYGOD", country: "India" },
      { name: "Goten", country: "India" },
      { name: "Kanha", country: "India" },
      { name: "SENSEI", country: "India", captain: true },
      { name: "Sam999", country: "India" },
    ],
  },
  {
    team: "Revenant XSpark",
    phase: "Quarter Finals",
    placement: 14,
    seed: "Qualifier",
    badges: ["Main", "Staff"],
    roster: [
      { name: "NinjaJOD", country: "India" },
      { name: "JDGamingYT", country: "India" },
      { name: "Pain09", country: "India" },
      { name: "Punkk", country: "India" },
      { name: "Tracegod", country: "India" },
    ],
  },
  {
    team: "Welt Esports",
    phase: "Quarter Finals",
    placement: 15,
    seed: "Qualifier",
    roster: [
      { name: "GokulWNL", country: "India", captain: true },
      { name: "Proton", country: "India" },
      { name: "Maxioso", country: "India" },
      { name: "Shyam", country: "India" },
      { name: "JustyOp", country: "India" },
    ],
  },
  {
    team: "Learn From Past",
    phase: "Quarter Finals",
    placement: 16,
    seed: "Qualifier",
    roster: [
      { name: "Termi", country: "India" },
      { name: "RushBoy", country: "India" },
      { name: "MAX", country: "India" },
      { name: "Honey", country: "India", captain: true },
      { name: "SHADOWW", country: "India" },
    ],
  },
  {
    team: "Nebula Esports",
    phase: "Wildcard",
    placement: 1,
    seed: "Qualifier",
    badges: ["Main", "Staff"],
    roster: [
      { name: "Aadi", country: "India", captain: true },
      { name: "KnowMe", country: "India" },
      { name: "KRATOS", country: "India" },
      { name: "Phoenix", country: "India" },
      { name: "Ryu", country: "India" },
    ],
  },
  {
    team: "Vanguard Esports",
    phase: "Wildcard",
    placement: 2,
    seed: "Qualifier",
    roster: [
      { name: "DreamS", country: "India", captain: true },
      { name: "Insidious", country: "India" },
      { name: "Dionysus", country: "India" },
      { name: "Crypto", country: "India" },
      { name: "AnujTooOP", country: "India" },
    ],
  },
  {
    team: "NoNx Esports",
    phase: "Wildcard",
    placement: 3,
    seed: "Qualifier",
    roster: [
      { name: "AimGoD", country: "India" },
      { name: "Anonymous", country: "India" },
      { name: "Arther", country: "India" },
      { name: "FAMEeeeee", country: "India" },
      { name: "Rapido", country: "India" },
    ],
  },
  {
    team: "K9 Esports",
    phase: "Wildcard",
    placement: 4,
    seed: "Qualifier",
    badges: ["Main", "Staff"],
    roster: [
      { name: "Knight", country: "India" },
      { name: "NinjaBoi", country: "India" },
      { name: "Omega", country: "India" },
      { name: "RyzenBOTX", country: "India" },
      { name: "Slug", country: "India" },
    ],
  },
  {
    team: "Victores Sumus",
    phase: "Wildcard",
    placement: 5,
    seed: "Qualifier",
    badges: ["Main", "Staff"],
    roster: [
      { name: "Owais", country: "India", captain: true },
      { name: "Mafia36", country: "India" },
      { name: "VeNoM", country: "India" },
      { name: "ScaryJod", country: "India" },
      { name: "Sarang", country: "India" },
    ],
  },
  {
    team: "Phoenix Esports",
    phase: "Wildcard",
    placement: 6,
    seed: "Qualifier",
    badges: ["Main", "Staff"],
    roster: [
      { name: "Saumraj", country: "India" },
      { name: "SIMP", country: "India" },
      { name: "Smoker46", country: "India" },
      { name: "Stranger", country: "India" },
      { name: "VipeR", country: "India" },
    ],
  },
  {
    team: "Reckoning Esports",
    phase: "Wildcard",
    placement: 7,
    seed: "Qualifier",
    roster: [
      { name: "Godx", country: "India" },
      { name: "Levi", country: "India" },
      { name: "Lovish", country: "India" },
      { name: "Roman", country: "India", captain: true },
      { name: "SahilOPAF", country: "India" },
    ],
  },
  {
    team: "Myth Official",
    phase: "Wildcard",
    placement: 8,
    seed: "Qualifier",
    roster: [
      { name: "Harshil", country: "India" },
      { name: "Lucifer", country: "India" },
      { name: "Daddy", country: "India" },
      { name: "Detrox", country: "India", captain: true },
      { name: "Aryton", country: "India" },
    ],
  },
];

export function getBgis2026ParticipantMap(normalizeTeam) {
  return Object.fromEntries(
    BGIS_2026_PARTICIPANTS.map((entry) => [normalizeTeam(entry.team), entry])
  );
}
