export const BMPS_2026_ROSTERS = {
  teamsoul: ["Goblin", "LEGIT", "NakuL", "Jokerr", "Thunder"],
  genesisesports: ["GravityJOD", "ViPER", "HunterZ", "FurY", "Zap"],
  orangutan: ["AKop", "WizzGOD", "Aaru", "Attanki"],
  victoressumus: ["VeNoM", "ScaryJod", "Owais", "Mafia36", "Paritosh"],
  godlikeesports: ["Saumay", "ADMINO", "Manya", "Spower", "Godz"],
  divinegaming: ["Slug", "NinjaBoi", "Omega", "Knight", "Amit"],
  revenantxspark: ["Proton", "Sukuna", "NinjaJOD", "Pain09", "Tracegod"],
  wyldfangs: ["SENSEI", "SPRAYGOD", "Goten", "Sam999", "Kanha"],
  vasistaesports: ["Beast", "A1mbot", "Hector", "Rony", "Dionysus"],
  nebulaesports: ["KnowMe", "Phoenix", "Aadi", "KRATOS", "Arjun"],
  learnfrompast: ["Honey", "MAX", "JDGamingYT", "Ryu", "Yash"],
  metaninza: ["Shadow7", "Fierce", "Apollo", "Auxin", "Javin"],
  mythofficial: ["Lucifer", "Daddy", "Detrox", "Harshil", "Aryton"],
  reckoningesports: ["Lovish", "Levi", "Roman", "SahilOPAF", "ProBGMI"],
  teamtamilas: ["Reaper", "AIMGOD", "MrIGL", "JustyOp", "MantyOP"],
  weltesports: ["GokulWNL", "Shyam", "Rico", "DragonOP", "PokoWNL"],
  lastadeesports: ["ShaDow", "Evil", "Kaalan", "SpyOp", "AFU"],
  "4trofficial": ["Anonymous", "VipeR", "Arther", "Rapido", "FlexJod"],
  "7godsesports": ["Moksh", "Vishu99", "Ninjuu", "Rexboy", "NinjA"],
  k9esports: ["Saumraj", "SnowJOD", "Taurus", "Smoker46", "Stranger"],
  troytamilianesports: ["Ayden", "Maxioso", "Lens06", "Hesperos", "Jazzy"],
  jaguaresports: ["BHAALU", "AVNISHOP", "Avanza", "SHOGUN", "PIXIEOP"],
  madkingsesports: ["SHADOW", "ClutchGod", "SIMP", "Troye", "Nobi"],
  whitewalkers: ["DreamS", "Veyron", "AnujTooOP", "Beast04", "Aryzen"],
  teamapexgaming: ["Jelly", "JONATHAN", "KioLmao", "Hydro", "Harsh"],
  "8bit": ["Juicy", "Sarang", "Skipz", "Shubh", "Shorty"],
  riotnationz: ["AADI", "Eezy", "Sunoj", "punk", "Dollar"],
  naqshesports: ["PmwiIGL", "OwenOG", "Skillfull", "InfGod", "Executor"],
  teamh4k: ["Sujal", "RageGod", "Wizard", "Mac", "Nodii"],
  higgbosonesports: ["Bunny", "HEROO", "RushBoy", "Godx", "WhiteTiger"],
  hadxesports: ["Cypher", "CEAZAR", "HOPE", "JAXXX", "Rishii"],
  windgodesports: ["RyzeN", "InfinityOP", "Kyzer", "Probot", "RIOO"],
  t7xorionesports: ["Cabeza03", "Mudit", "Fantom09", "Firoo07", "Reverse"],
  nonxesports: ["Aman", "Syrus", "Stunner", "Hexy", "DGbot"],
  blinkesports: ["MaYaNK", "Profesir", "Jayesh", "HardikUG", "NexXuS"],
  "7acesxtrbesports": ["Coder", "Kraxx", "Gonu", "Ammyjod", "Rolex"],
  genxfmesports: ["dipop", "damuuu78", "ghost", "buNnY14", "moGLiOp"],
  teamflyingesports: ["WhyBro1", "JATT", "Hunter", "notKnowme", "Cobra"],
  mysterious4: ["GOKU", "Naman", "Nooob", "KRSNAJOD19", "Henry"],
  thundergodsxtortugagaming: ["Abhi", "Fragger", "Clozy9", "Icy", "Rambo"],
  aresesport: ["ErrorOG", "BIJOY", "Knuckle", "BAITERR", "CluTchBoi"],
  likithaesports: ["DanieL", "INFERNOO", "Starboyy", "Zemo", "Fusion"],
  santaesports: ["Alpha05", "ADONIS", "PUNISHER11", "CoFFIN", "BanditGod"],
  risingesports: ["BeardBaba", "EzOL", "FouL619", "YuvaOP", "FoxOP"],
  godsentlegions: ["HarshOg", "Master", "ToXic26", "Emperor", "Skepp"],
  rapidchaosesports: ["FLASH", "Psycho", "Toxic", "DhruvG", "fragger"],
  zeroarkofficial: ["Morty", "PAINisLIVE", "JatinOG", "ChandanOp", "SarwarOG"],
  auraxesports: ["Wanted", "KrisOp", "FraggerNub", "KALYUG", "Dope"],
  teamaryan: ["Aryan", "Devotee", "Syrax", "Raiden", "PRO"],
  someonesdream: ["Dizzy18", "Iscream26", "Ghostfxce", "KaranNotOP", "Goten69"],
  teamdoxy: ["Doxy", "Unq21", "DeathGOD", "YepezZzZ", "BeasTboyyyy"],
  jaapiesports: ["Dreamss", "ExploseR", "SKOP", "CatalysT", "Ghost"],
  oopsofficial: ["RaiX", "AffuOP", "Element", "Reaper", "Zentrix777"],
  teamversatile: ["Rexx64", "SmoKeR", "ClixOp", "Spartan9", "Keshu99"],
  autobotzesports: ["EGGY", "Lobster", "Ralphie", "Areeb", "FanOP"],
  phoenixesports: ["EclipseOP", "frenzyOkoK", "VENGEANCE", "Faith", "Arnav"],
  futuriseesportsempireoriginals: [
    "Norm4nJR",
    "Commando",
    "WarBoy",
    "ToNY",
    "Shooter9",
  ],
  godsreign: ["Neyo", "Justin", "DeltaPG", "AquaNox", "Destro"],
  teamredxross: ["Lucifer999", "Armxn", "Zeref", "Superb", "Amaan"],
  dcxscresports: ["TapGod", "Arto", "Chokeboy", "YprBolte", "Harshu"],
  godsentesports: ["FraGGy19", "Levii911", "JunaidOG", "HunTRO", "Revenge4uu"],
  quantumsparks: ["Sc0utOP", "MasTer", "Archit", "Yashu", "Daksh"],
  truerippers: ["Punkk", "Omega", "Termi", "Shayaan", "Achuk"],
  esportsocial: ["BaDop", "MannyJOD", "GyroGOD", "Joyesh", "SuperMan"],
};
