function normalizePlayerPhotoKey(value) {
  return String(value || "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "");
}

const PLAYER_PHOTO_OVERRIDES = {
  // GodLike Esports
  admino: "/images/players/GodlAdmino.png",
  godz: "/images/players/GodlGodzz.png",
  godzz: "/images/players/GodlGodzz.png",
  spower: "/images/players/GodlSpower.png",
  manya: "/images/players/GodlManya.png",
  saumay: "/images/players/GodlSaumay.png",
  // Other BMPS teams
  aadi: "/images/players/AADII.png",
  aadii: "/images/players/AADII.png",
  aaru: "/images/players/aaru.png",
  ak: "/images/players/akop.png",
  akop: "/images/players/akop.png",
  attanki: "/images/players/attanki.png",
  wizzgod: "/images/players/wizzgod.png",
  scaryjod: "/images/players/scaryjod.png",
  slug: "/images/players/SLUG.png",
  aimgodd: "/images/players/Aimgodd.png",
  aimgod: "/images/players/Aimgodd.png",
  // BMPS players with images
  fury: "/images/players/FURY.png",
  goblin: "/images/players/GOBLIN.png",
  gravity: "/images/players/GRAVITY.png",
  gravityjod: "/images/players/GRAVITY.png",
  hamsig: "/images/players/HAMSIG.png",
  hunterz: "/images/players/HUNTERZ.png",
  juicy: "/images/players/JUICY.png",
  kamikaze: "/images/players/KAMIKAZE.png",
  legit: "/images/players/LEGIT.png",
  lost: "/images/players/LOST.png",
  mafia: "/images/players/MAFIA.png",
  nakul: "/images/players/NAKUL.png",
  ninjajod: "/images/players/Ninja Jod.png",
  owais: "/images/players/OWAIS.png",
  paritosh: "/images/players/PARITOSH.png",
  prem: "/images/players/PREM.png",
  qx: "/images/players/QXZZ.png",
  qxzz: "/images/players/QXZZ.png",
  qxzzz: "/images/players/QXZZ.png",
  refus: "/images/players/REFUS.png",
  ripsevinnn: "/images/players/RIPSEVINNN.png",
  saumraj: "/images/players/SAUMRAJ.png",
  shubh: "/images/players/SHUBH.png",
  skipz: "/images/players/SKIPZ.png",
  smoker46: "/images/players/SMOKER46.png",
  snowjod: "/images/players/SNOWJOD.png",
  soez: "/images/players/SOEZ.png",
  solkay: "/images/players/SOLKAY.png",
  solkay3: "/images/players/SOLKAY.png",
  taurus: "/images/players/TAURUS.png",
  thunder: "/images/players/THUNDER.png",
  trace: "/images/players/Trace.png",
  tracegod: "/images/players/Trace.png",
  venom: "/images/players/VENOM.png",
  viper: "/images/players/VIPER.png",
  xzy: "/images/players/XZY.png",
  zap: "/images/players/ZAP.png",
  zyol: "/images/players/ZYOL.png",
  zyoll: "/images/players/ZYOL.png",
  dokc: "/images/players/DOKC.png",
  east: "/images/players/EAST.png",
  dragonop: "/images/players/DRAGONOP.png",
  frentzy: "/images/players/Frentzy.png",
  heroo: "/images/players/HEROO.png",
  levii: "/images/players/LEVII.png",
  levi: "/images/players/LEVII.png",
  ninjaboi: "/images/players/NINJABOI.png",
  neyo: "/images/players/NEYO.png",
  aquanox: "/images/players/AQUANOX.png",
  destro: "/images/players/DESTRO.png",
  justin: "/images/players/JUSTIN.png",
  deltapg: "/images/players/DELTAPG.png",
  nofear: "/images/players/NOFEAR.png",
  smile: "/images/players/Smile.png",
  punkk: "/images/players/PUNKK.png",
  reiji: "/images/players/Reiji.png",
  ReijiOcO: "/images/players/Reiji.png",
  revo: "/images/players/Revo.png",
  REVO77K: "/images/players/Revo.png",
  spraygod: "/images/players/SPRAYGOD.png",
  favian: "/images/players/FAVIAN.png",
  // Top 5 MVP players
  jonathan: "/images/players/Jonathan.png",
  sarang: "/images/players/Sarang.png",
  jokerr: "/images/players/Jokerr.png",
  // PMWC 2026 players
  qzz: "/images/players/QZZ.png",
  sleepy: "/images/players/Sleepy.png",
  hyunbin: "/images/players/HYUNBIN.png",
  tiz1: "/images/players/TIZI.png",
  tizi: "/images/players/TIZI.png",
  iq: "/images/players/IQ.png",
  dok: "/images/players/DOK.png",
  top: "/images/players/TOP.png",
  rosemary: "/images/players/Rosemary.png",
  nolbu: "/images/players/Nolbu.png",
  "3more": "/images/players/3More.png",
  loxy: "/images/players/Loxy.png",
  // PMGC 2025 special award players
  kecth: "/images/players/Kecth.png",
  ceolater: "/images/players/CEOLATER.png",
  morman: "/images/players/MORMAN.png",
  ternyk: "/images/players/TernyK.png",
  // Unmapped files on disk
  arjun: "/images/players/ARJUN.png",
  knowme: "/images/players/KNOWME.png",
  kratos: "/images/players/KRATOS.png",
  phoenix: "/images/players/PHOENIX.png",
  bay: "/images/players/BAY.png",
  paraboy: "/images/players/PARABOY.png",
  shanz: "/images/players/SHANZ.png",
  suki: "/images/players/SUKI.png",
  suk: "/images/players/SUK.png",
  lingsha: "/images/players/LINGSHA.png",
  termi: "/images/players/TERMI.png",
  sky: "/images/players/SKY.png",
  painislive: "/images/players/PAINISLIVE.png",
  pain09: "/images/players/PAIN09.png",
  jiggl3: "/images/players/JIGGL3.png",
  henry: "/images/players/HENRY.png",
  devotee: "/images/players/DEVOTEE.png",
  beast: "/images/players/BEAST.png",
  harsh: "/images/players/HARSH.png",
  jelly: "/images/players/JELLY.png",
  hydro: "/images/players/HYDRO.png",
  kiolmao: "/images/players/KioLmao.png",
  mafia36: "/images/players/MAFIA36.png",
  huzaifa: "/images/players/HUZAIFA.png",
  falak: "/images/players/FALAK.png",
  t24op: "/images/players/T24Op.png",
  // Award winners needing photos on disk
  amoori: "/images/players/3More.png",
  shanzhi: "/images/players/SHANZ.png",
};

export function getPlayerPhotoByIgn(ign) {
  return PLAYER_PHOTO_OVERRIDES[normalizePlayerPhotoKey(ign)] || null;
}
