export const TEAM_TRANSFERS = [
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["FoxOP"],
    oldTeam: "iQOO Team Tamilas",
    newTeam: null,
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["MantyOP", "JustyOP"],
    oldTeam: null,
    newTeam: "iQOO Team Tamilas",
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["Pro", "SkillFull"],
    oldTeam: "Autobotz Esports",
    newTeam: null,
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["FanOP", "Eggy666"],
    oldTeam: null,
    newTeam: "Autobotz Esports",
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["JustyOP"],
    oldTeam: "Welt Esports",
    newTeam: null,
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["DragonOP", "Rico", "PokoWNL"],
    oldTeam: null,
    newTeam: "Welt Esports",
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["Punkk", "JDGamingYT"],
    oldTeam: "Revenant XSpark",
    newTeam: null,
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["Sukuna", "Proton"],
    oldTeam: null,
    newTeam: "Revenant XSpark",
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["JONATHAN"],
    oldTeam: "GodLike Esports",
    newTeam: null,
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["AquaNox"],
    oldTeam: null,
    newTeam: "Gods Reign",
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["Saumay"],
    oldTeam: null,
    newTeam: "GodLike Esports",
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["Knight", "NinjaBoi", "Omega", "RyzenBOTX", "Slug"],
    oldTeam: "K9 Esports",
    newTeam: null,
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["Stranger", "Saumraj", "Smoker46", "Taurus", "SnowJOD"],
    oldTeam: null,
    newTeam: "K9 Esports",
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["Jelly", "KioLmao", "Hydro", "Harsh", "Rony"],
    oldTeam: "True Rippers",
    newTeam: null,
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["Jonathan", "Jelly", "KioLmao", "Harsh", "Hydro"],
    oldTeam: null,
    newTeam: "Apex Gaming",
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["Ryu"],
    oldTeam: "Nebula Esports",
    newTeam: null,
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["Arjun"],
    oldTeam: null,
    newTeam: "Nebula Esports",
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["Godx"],
    oldTeam: "Reckoning Esports",
    newTeam: null,
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["Pro"],
    oldTeam: null,
    newTeam: "Reckoning Esports",
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["Raiden"],
    oldTeam: "8Bit",
    newTeam: null,
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["Shubh"],
    oldTeam: null,
    newTeam: "8Bit",
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["Sreyam", "Nadegod", "Wixxy"],
    oldTeam: "Team Versatile",
    newTeam: null,
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["Saumay", "FusionOP", "Shayaan"],
    oldTeam: "Vasista Esports",
    newTeam: null,
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["Rony", "Aimbot", "Dionysus"],
    oldTeam: null,
    newTeam: "Vasista Esports",
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["Henry", "Aimbot"],
    oldTeam: "Team Aryan",
    newTeam: null,
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["Syrax", "Pro", "Raiden"],
    oldTeam: null,
    newTeam: "Team Aryan",
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["Sarang"],
    oldTeam: "Victores Sumus",
    newTeam: null,
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["Paritosh"],
    oldTeam: null,
    newTeam: "Victores Sumus",
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["AimGoD", "Anonymous", "Arther", "FAMEeeeee", "Rapido"],
    oldTeam: "NoNx Esports",
    newTeam: null,
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["Syrax", "Pro"],
    oldTeam: "Madkings Esports",
    newTeam: null,
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["DragonOP", "Rico", "PokoWNL"],
    oldTeam: "Rising Esports",
    newTeam: null,
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["Dope", "Phantom", "Shogun"],
    oldTeam: "Los Hermanos Esports",
    newTeam: null,
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["Shiraj", "RyzenBotx", "ShubOG"],
    oldTeam: null,
    newTeam: "Los Hermanos Esports",
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["Morty", "PainIsLive", "ZGOD", "AKOP", "Utkarsh"],
    oldTeam: "4TR Official",
    newTeam: null,
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["Anonymous", "Arther", "Viper", "Rapido", "Flexjod"],
    oldTeam: null,
    newTeam: "4TR Official",
  },
  {
    window: "April 2026 Transfer Window",
    date: "2026-04-30",
    country: "India",
    players: ["Whitetiger", "Javin"],
    oldTeam: "Meta Ninza",
    newTeam: null,
  },
];
