const TEAM_LOGOS = [
  { pattern: /^(2OP Official|2oP Official)$/i, src: "/images/team-logos/2op.png" },
  { pattern: /^(4Merical Esports)$/i, src: "/images/team-logos/4merical-esports.png" },
  { pattern: /^(4TR Official)$/i, src: "/images/team-logos/4tr-official.png" },
  { pattern: /^(4 Wolf x DOD|4Wolf x DoD)$/i, src: "/images/team-logos/4wolf-dod.png" },
  { pattern: /^(8Bit|iQOO 8bit|8Bit x CS Esports)$/i, src: "/images/team-logos/8bit.png" },
  { pattern: /^(Aryan x TMG Gaming|Team Aryan)$/i, src: "/images/team-logos/aryan-x-tmg-gaming.png" },
  { pattern: /^(Team Apex Gaming|Apex Gaming)$/i, src: "/images/team-logos/team-apex-gaming.png" },
  { pattern: /^Autobotz Esports$/i, src: "/images/team-logos/autobotz-esports.png" },
  { pattern: /^Aura X Esports$|^Aurax Esports$/i, src: "/images/team-logos/aurax-esports.png" },
  { pattern: /^Ares Esport$|^Ares Esports$/i, src: "/images/team-logos/ares-esport.png" },
  { pattern: /^BIG BROTHER ESPORTS$/i, src: "/images/team-logos/big-brother-esports.png" },
  { pattern: /^Blink Esports$/i, src: "/images/team-logos/blink-esports.png" },
  { pattern: /^(Blind eSports|Blind Esports)$/i, src: "/images/team-logos/blind.png" },
  { pattern: /^Bot Army$/i, src: "/images/team-logos/bot-army.png" },
  { pattern: /^CAG OSAKA$/i, src: "/images/team-logos/cag-osaka.png" },
  { pattern: /^Carnival Gaming$/i, src: "/images/team-logos/carnival-gaming.png" },
  { pattern: /^Cincinnati Kids$/i, src: "/images/team-logos/cincinnati-kids.png" },
  { pattern: /^(Dplus|Dplus KIA)$/i, src: "/images/team-logos/dplus-kia.png" },
  { pattern: /^DRX$/i, src: "/images/team-logos/drx.png" },
  { pattern: /^DUKSAN Esports$/i, src: "/images/team-logos/duksan-esports.png" },
  { pattern: /^(DCxSCR Esports|DCXSCR Esports|Team DCxSCR)$/i, src: "/images/team-logos/dcxscr-esports.png" },
  { pattern: /^(Divine|Divine Gaming)$/i, src: "/images/team-logos/divine-gaming.png" },
  { pattern: /^(emTek StormX|EntityxVST)$/i, src: "/images/team-logos/emtek-stormx.png" },
  { pattern: /^(Entity|Entity Gaming)$/i, src: "/images/team-logos/entity.png" },
  { pattern: /^(Esport Social|Esports Social)$/i, src: "/images/team-logos/esport-social.png" },
  { pattern: /^EvoX Esports$/i, src: "/images/team-logos/evox.png" },
  { pattern: /^(FS Esports|FS eSports)$/i, src: "/images/team-logos/fs-esports.png" },
  { pattern: /^(Futurise x Empire|Futurise x Empire Originals|Futurise Empire Originals|Futurise Esports Empire Originals|Empire Originals)$/i, src: "/images/team-logos/futurise-x-empire.png" },
  { pattern: /^Genesis Esports$/i, src: "/images/team-logos/genesis.png" },
  { pattern: /^(GenXFM Esports|GENxFM Esports|GenxFM Esports)$/i, src: "/images/team-logos/genxfm-esports.png" },
  { pattern: /^(Gladiators Esports|Gladiator Esports)$/i, src: "/images/team-logos/gladiators-esports.png" },
  { pattern: /^GlitchXReborn$/i, src: "/images/team-logos/glitchxreborn.png" },
  { pattern: /^Global Esports$/i, src: "/images/team-logos/global-esports.png" },
  { pattern: /^(Godsent Legion|Godsent Legions)$/i, src: "/images/team-logos/godsent-legions.png" },
  { pattern: /^(Godsent Esports|Godscent Esports)$/i, src: "/images/team-logos/godsent-esports.png" },
  { pattern: /^7Gods Esports$/i, src: "/images/team-logos/7gods-esports.png" },
  { pattern: /^(Hero Xtreme GodLike|GodLike Esports)$/i, src: "/images/team-logos/godlike.png" },
  { pattern: /^Gods Omen$/i, src: "/images/team-logos/gods-omen.png" },
  { pattern: /^(Gods Reign|OnePlus Gods Reign)$/i, src: "/images/team-logos/gods-reign.png" },
  { pattern: /^(Higg Boson|Higg Boson Esports|Higgboson Esports)$/i, src: "/images/team-logos/higg-boson.png" },
  { pattern: /^HADX Esports$|^HADX$/i, src: "/images/team-logos/hadx-esports.png" },
  { pattern: /^HYDERABAD HYDRAS$|^Hyderabad Hydras$/i, src: "/images/team-logos/hyderabad-hydras.png" },
  { pattern: /^(HYDRA OFFICIAL|Hydra)$/i, src: "/images/team-logos/hydra.png" },
  { pattern: /^(Rising Inferno Esports|Rising Esports|Inferno Squad|Hail Inferno Squad)$/i, src: "/images/team-logos/inferno-squad.png" },
  { pattern: /^(Jecheon PhalanX|Jecheon Phalanx)$/i, src: "/images/team-logos/jecheon-phalanx.png" },
  { pattern: /^Jaapi Esports$/i, src: "/images/team-logos/jaapi-esports.png" },
  { pattern: /^Jaguar Esports$/i, src: "/images/team-logos/jaguar-esports.png" },
  { pattern: /^K9 Esports$/i, src: "/images/team-logos/k9.png" },
  { pattern: /^Lastade Esports$/i, src: "/images/team-logos/lastade-esports.png" },
  { pattern: /^Likitha Esports$/i, src: "/images/team-logos/likitha-esports.png" },
  { pattern: /^Learn From Past$/i, src: "/images/team-logos/learn-from-past.png" },
  { pattern: /^(Los hermanos|Los Hermanos Esports)$/i, src: "/images/team-logos/los-hermanos-esports.png" },
  { pattern: /^(MadKings|Madkings|Madkings Esports)$/i, src: "/images/team-logos/madkings.png" },
  { pattern: /^MAKING THE ROAD$/i, src: "/images/team-logos/making-the-road.png" },
  { pattern: /^Maru Gaming$/i, src: "/images/team-logos/maru-gaming.png" },
  { pattern: /^Medal Esports$/i, src: "/images/team-logos/medal-esports.png" },
  { pattern: /^Meta Ninza$/i, src: "/images/team-logos/meta-ninza.png" },
  { pattern: /^MOGO Esports$/i, src: "/images/team-logos/mogo-esports.png" },
  { pattern: /^(MYSTERIOUS 4|mysterious4 Esports)$/i, src: "/images/team-logos/mysterious-4.png" },
  { pattern: /^Myth Official$/i, src: "/images/team-logos/myth.png" },
  { pattern: /^(Naqsh Esports|M4 x Naqsh Esports)$/i, src: "/images/team-logos/naqsh-esports.png" },
  { pattern: /^Nebula Esports$/i, src: "/images/team-logos/nebula.png" },
  { pattern: /^(Nongshim RedForce|NS RedForce)$/i, src: "/images/team-logos/nongshim-redforce.png" },
  { pattern: /^(NONx Esports|NoNx Esports|THWxNonx Esports)$/i, src: "/images/team-logos/nonx.png" },
  { pattern: /^(Numen Esports|Numen Gaming)$/i, src: "/images/team-logos/numen-esports.png" },
  { pattern: /^(OR Esports|OREsports)$/i, src: "/images/team-logos/oresports.png" },
  { pattern: /^Oops Official$/i, src: "/images/team-logos/oops-official.png" },
  { pattern: /^(IQOO Orangutan|Orangutan)$/i, src: "/images/team-logos/orangutan.png" },
  { pattern: /^Phoenix Esports$/i, src: "/images/team-logos/phoenix.png" },
  { pattern: /^Quantum Sparks$/i, src: "/images/team-logos/quantum-sparks.png" },
  { pattern: /^Rapid Chaos Esports$/i, src: "/images/team-logos/rapid-chaos-esports.png" },
  { pattern: /^(IQOO Reckoning Esports|Reckoning Esports)$/i, src: "/images/team-logos/reckoning.png" },
  { pattern: /^(Team RedXRoss|TeamRedXross|RedXRoss|4EverxRedXRoss)$/i, src: "/images/team-logos/team-redxross.png" },
  { pattern: /^REJECT$/i, src: "/images/team-logos/reject.png" },
  { pattern: /^REIGNITE$/i, src: "/images/team-logos/reignite.png" },
  { pattern: /^(IQOO Revenant XSpark|Revenant XSpark|Revenant Esports)$/i, src: "/images/team-logos/revenant-xspark.png" },
  { pattern: /^(Riot Nationz|RiotNationz|RiotNations)$/i, src: "/images/team-logos/riotnationz.png" },
  { pattern: /^Rivalry NRI$|^RIVALRY x NRI$/i, src: "/images/team-logos/rivalry-nri.png" },
  { pattern: /^(ROX|ROX Esports)$/i, src: "/images/team-logos/rox-esports.png" },
  { pattern: /^Silly Esports$/i, src: "/images/team-logos/silly-esports.png" },
  { pattern: /^Sinewy Esports$/i, src: "/images/team-logos/sinewy.png" },
  { pattern: /^SOA ESPORTS$|^SOA Esports$/i, src: "/images/team-logos/soa-esports.png" },
  { pattern: /^(Santa Esports|Santa ESP)$/i, src: "/images/team-logos/santa-esports.png" },
  { pattern: /^SomeOnes Dream$/i, src: "/images/team-logos/someones-dream.png" },
  { pattern: /^(IQOO SouL|Team SouL|Team Soul|iQOO Soul)$/i, src: "/images/team-logos/soul.png" },
  { pattern: /^(Hades H4K|TEAM H4K|H4K Esports)$/i, src: "/images/team-logos/h4k.png" },
  { pattern: /^(7Aces|7 Aces|7Aces x TRB|7AcesxTRB|7ACExTRB|7AcesXTRB Esports)$/i, src: "/images/team-logos/7aces.png" },
  { pattern: /^Team Doxy$/i, src: "/images/team-logos/team-doxy.png" },
  { pattern: /^(Team Fly|Team Flying Esports|FLY)$/i, src: "/images/team-logos/team-fly.png" },
  { pattern: /^Team Forever$/i, src: "/images/team-logos/team-forever.png" },
  { pattern: /^(T7xOrion Esports|T7xOrion|T7 x Orion Esports)$/i, src: "/images/team-logos/t7xorion-esports.png" },
  { pattern: /^(TEAM iNSANE|Team Insane|Team Insane Esports)$/i, src: "/images/team-logos/team-insane.png" },
  { pattern: /^Team Limra$/i, src: "/images/team-logos/team-limra.png" },
  { pattern: /^(IQOO Team Tamilas|Team Tamilas)$/i, src: "/images/team-logos/team-tamilas.png" },
  { pattern: /^Team Versatile$/i, src: "/images/team-logos/team-versatile.png" },
  { pattern: /^(ThunderGods X Tortuga Gaming|Thundergods Tortuga Gaming|Thundergods Esports)$/i, src: "/images/team-logos/thundergods-x-tortuga-gaming.png" },
  { pattern: /^(TeamXSpark|Team X Spark)$/i, src: "/images/team-logos/xspark.png" },
  { pattern: /^(Troy Tamilan Esports|Troy Tamilans|Troy Tamilans Esports|Troy Tamilian Esports)$/i, src: "/images/team-logos/troy-tamilian-esports.png" },
  { pattern: /^(Infinix TrueRippers|True Rippers|True Rippers x Infinix)$/i, src: "/images/team-logos/true-rippers.png" },
  { pattern: /^TWM Gaming$/i, src: "/images/team-logos/twm-gaming.png" },
  { pattern: /^TWOB$/i, src: "/images/team-logos/twob.png" },
  { pattern: /^(Team Vanguard|Vanguard Esports)$/i, src: "/images/team-logos/vanguard.png" },
  { pattern: /^Vasista Esports$/i, src: "/images/team-logos/vasista.png" },
  { pattern: /^Victores Sumus$/i, src: "/images/team-logos/victores-sumus.png" },
  { pattern: /^Welt Esports$/i, src: "/images/team-logos/welt.png" },
  { pattern: /^White Walkers$/i, src: "/images/team-logos/white-walkers.png" },
  { pattern: /^WindGod Esports$/i, src: "/images/team-logos/windgod-esports.png" },
  { pattern: /^Wyld Fangs$/i, src: "/images/team-logos/wyld-fangs.png" },
  { pattern: /^Zero Ark Official$/i, src: "/images/team-logos/zero-ark-official.png" },
  { pattern: /^(ZZ|ZZ ESPORTS)$/i, src: "/images/team-logos/zz-esports.png" },
];

const LOW_CONTRAST_TEAM_LOGOS = [
  /^(Esport Social|Esports Social)$/i,
  /^(Quantum Sparks)$/i,
  /^(DCxSCR Esports|DCXSCR Esports|Team DCxSCR)$/i,
  /^(Divine|Divine Gaming)$/i,
  /^(Futurise x Empire|Futurise x Empire Originals|Futurise Empire Originals|Futurise Esports Empire Originals|Empire Originals)$/i,
  /^(Godsent Legion|Godsent Legions)$/i,
  /^(HADX Esports|HADX)$/i,
  /^(Naqsh Esports|M4 x Naqsh Esports)$/i,
  /^(Team Apex Gaming|Apex Gaming)$/i,
  /^(White Walkers)$/i,
  /^(Rising Inferno Esports|Rising Esports|Inferno Squad|Hail Inferno Squad)$/i,
  /^(Zero Ark Official)$/i,
  /^(IQOO SouL|Team SouL|Team Soul|iQOO Soul)$/i,
  /^(IQOO Orangutan|Orangutan)$/i,
  /^(8Bit|iQOO 8bit|8Bit x CS Esports)$/i,
  /^(IQOO Team Tamilas|Team Tamilas)$/i,
  /^(IQOO Reckoning Esports|Reckoning Esports)$/i,
  /^(IQOO Revenant XSpark|Revenant XSpark|Revenant Esports)$/i,
];

const WIDE_TEAM_LOGOS = [
  /^(IQOO SouL|Team SouL|Team Soul|iQOO Soul)$/i,
  /^(IQOO Orangutan|Orangutan)$/i,
  /^(8Bit|iQOO 8bit|8Bit x CS Esports)$/i,
  /^(IQOO Team Tamilas|Team Tamilas)$/i,
  /^(IQOO Reckoning Esports|Reckoning Esports)$/i,
  /^(IQOO Revenant XSpark|Revenant XSpark|Revenant Esports)$/i,
  /^(DCxSCR Esports|DCXSCR Esports|Team DCxSCR)$/i,
  /^(Futurise x Empire|Futurise x Empire Originals|Futurise Empire Originals|Futurise Esports Empire Originals|Empire Originals)$/i,
  /^(7Aces|7 Aces|7Aces x TRB|7AcesxTRB|7ACExTRB|7AcesXTRB Esports)$/i,
  /^(T7xOrion Esports|T7xOrion|T7 x Orion Esports)$/i,
];

export function getTeamLogoByName(teamName) {
  if (!teamName) return null;

  const match = TEAM_LOGOS.find((entry) => entry.pattern.test(teamName));
  return match?.src ?? null;
}

export function isLowContrastTeamLogo(teamName) {
  if (!teamName) return false;
  return LOW_CONTRAST_TEAM_LOGOS.some((pattern) => pattern.test(teamName));
}

export function isWideTeamLogo(teamName) {
  if (!teamName) return false;
  return WIDE_TEAM_LOGOS.some((pattern) => pattern.test(teamName));
}
