services:
  - type: web
    name: core-esports
    runtime: docker
    plan: free
    healthCheckPath: /api/health
    dockerBuildArgs:
      - VITE_GOOGLE_CLIENT_ID=13045307296-v52idel7q4medhlhedjciv4qeq0e964e.apps.googleusercontent.com
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORE_AUTH_SESSION_SECRET
        generateValue: true
      - key: CORE_ADMIN_EMAILS
        value: sathkrishna3@gmail.com
      - key: GOOGLE_CLIENT_ID
        value: 13045307296-v52idel7q4medhlhedjciv4qeq0e964e.apps.googleusercontent.com
      - key: FRONTEND_ORIGIN
        value: https://core-esports-1ibg.onrender.com
