/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    extend: {
      fontFamily: {
        body: ["var(--font-body)"],
        heading: ["var(--font-heading)"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        brand: {
    "ink-deep": "#050505",
    "navy-darkest": "#050f1e",
    "navy-black": "#08111e",
    "navy-abyss": "#0d1727",
    "navy-dark": "#0e4d9f",
    "ink-black": "#0f0a08",
    "ink-slate": "#0f172a",
    "navy-night": "#101a2a",
    "navy-void": "#101b2d",
    "emerald": "#10b981",
    "ink-pure": "#111111",
    "ink": "#11131a",
    "ink-slate-2": "#111827",
    "mint-deepsea": "#11311f",
    "ink-void": "#121418",
    "navy-storm": "#121f33",
    "mint-abyss": "#12323a",
    "navy-royal": "#1357b0",
    "navy-deep": "#1362c5",
    "navy-ink": "#1562c4",
    "navy-bright": "#1565c0",
    "violet-abyss": "#160d27",
    "ink-soft": "#161616",
    "navy-midnight": "#16263d",
    "navy": "#165ca8",
    "navy-dusk": "#172740",
    "ink-hover": "#181c24",
    "mint-deep": "#18b7a0",
    "ink-char": "#1a1b1e",
    "ink-mute": "#1a1d26",
    "ink-mid": "#1a202c",
    "navy-gloom": "#1a2940",
    "sky-bright": "#1a73e8",
    "ink-soft-3": "#1c1c1c",
    "navy-mid": "#1c66bc",
    "ink-soft-2": "#1d1d1d",
    "sky-azure": "#1e88e5",
    "mint-forest-2": "#1f6f71",
    "mint-lime": "#20e6a8",
    "gold-espresso-2": "#26160f",
    "coral-cocoa": "#29141a",
    "coral-berry": "#2d1419",
    "ink-dim": "#2d3138",
    "mint-forest": "#2d8f8d",
    "navy-sky": "#2e7bd2",
    "ink-steel": "#2f3541",
    "slate-graphite": "#30343c",
    "sky-clear": "#38bdf8",
    "gold-mocha": "#3b3022",
    "sky-deep": "#3b82c4",
    "sky-royal": "#3b82f6",
    "coral-maroon": "#3d1620",
    "gold-olive": "#3f311a",
    "slate-ink": "#414854",
    "ink-faint": "#444444",
    "violet-night": "#45256d",
    "sky-mid": "#467fca",
    "slate-dim": "#49505b",
    "coral-wine": "#4b1822",
    "sky-ink": "#4b5f7d",
    "rose-maroon": "#591012",
    "gold-earth": "#5a441c",
    "violet-deep-2": "#5b3ab2",
    "coral-wine-soft": "#5c212c",
    "slate": "#5c6472",
    "mint-dune": "#5e6664",
    "sky-border": "#5e9ae6",
    "gold-espresso": "#5f4825",
    "slate-stone": "#636363",
    "slate-bone": "#666666",
    "mint": "#67c9bb",
    "violet-royal": "#6936dd",
    "slate-faint": "#6a6f78",
    "coral-plum": "#6b3741",
    "violet-deep": "#6c49d1",
    "slate-soft": "#6d7278",
    "slate-ash": "#707987",
    "sky-link": "#72adf1",
    "mint-sea": "#79b7b2",
    "slate-gray": "#7a7a7a",
    "rose-dark": "#7b3842",
    "mint-mist-2": "#7bb5b1",
    "sky": "#7ec8ff",
    "taupe-dark": "#80705f",
    "taupe": "#8a7866",
    "slate-cool": "#8b919a",
    "slate-mist": "#8b9ab6",
    "violet-mid": "#8f58f3",
    "slate-mute": "#8f949c",
    "slate-400": "#94a3b8",
    "slate-ash-soft": "#98a0ae",
    "taupe-deep": "#9c8368",
    "rose-berry-2": "#9d1725",
    "violet": "#a573ff",
    "coral-brick": "#a86837",
    "slate-fog": "#aeb3bf",
    "rose-bright-2": "#af1430",
    "gold-mid-dark": "#b08f4a",
    "lime": "#b2ff59",
    "amber-deep": "#b45309",
    "coral-clay": "#b56b48",
    "rose-berry": "#b9384f",
    "gold-deep": "#b98516",
    "gold-bronze": "#c4a452",
    "violet-pale": "#c4b0ff",
    "coral-burnt": "#c85f35",
    "border-stone": "#c8c1b5",
    "coral-tan": "#cc9a68",
    "sky-cloud": "#cdd7e1",
    "mint-frost": "#cef6ef",
    "coral-bronze": "#cf9660",
    "gold-mid": "#cfad54",
    "gold-pale": "#cfb77a",
    "sky-dusk": "#cfd9e4",
    "rose-deep": "#d04b62",
    "gold": "#d0ad63",
    "rose-crimson": "#d32035",
    "rose-wine": "#d45c72",
    "border-lift-2": "#d7c5b1",
    "sky-mist": "#d7e5f7",
    "violet-soft": "#d8b8ff",
    "border-hover": "#d8c8b4",
    "sky-breeze": "#d8e0eb",
    "mint-fog": "#d8faf2",
    "border-lift": "#d9c7b3",
    "border-faint": "#d9ccbb",
    "mint-ice": "#d9fbf5",
    "rose-bright": "#db3b54",
    "sky-wash": "#dce4ec",
    "mint-mist": "#dcfbf5",
    "mint-ice-bright": "#dcffff",
    "sky-fog": "#dde3eb",
    "sky-haze": "#dde5ee",
    "rose-bloom": "#df6f85",
    "sky-soft": "#dfe6ee",
    "sky-pale": "#dfe7f0",
    "border-gray": "#e0e0e0",
    "border-sand": "#e6ddd2",
    "border-tan": "#e7ddd1",
    "cream-line": "#e7e7e7",
    "cream-edge-soft": "#e8e8e8",
    "gold-sand": "#e9d29b",
    "border": "#eadfce",
    "border-warm": "#ebdfcf",
    "border-linen": "#ebe2d6",
    "mint-fog-2": "#ebfaf6",
    "rose-pale": "#ec6970",
    "cream-edge": "#ececec",
    "cream-fog": "#ededed",
    "sky-linen": "#edf2f7",
    "border-ivory": "#eee4d8",
    "mint-ice-2": "#eefefd",
    "cream-line-soft": "#efefef",
    "gold-sand-soft": "#f0dc9c",
    "cream-beige": "#f0e7dc",
    "cream-fog-2": "#f0f0f0",
    "violet-mist": "#f2e3ff",
    "cream-haze-2": "#f2f5f3",
    "coral-apricot": "#f3a06f",
    "violet-frost": "#f3e6ff",
    "gray-100": "#f3f4f6",
    "cream-mist": "#f4f4f2",
    "amber": "#f59e0b",
    "cream-frost-2": "#f5f7fa",
    "mint-ice-soft": "#f5fffe",
    "gold-oat": "#f6d6aa",
    "gold-champagne": "#f6e8a7",
    "cream-sand": "#f6f5f3",
    "gold-peach-2": "#f7e4ce",
    "cream-bg": "#f7efe6",
    "violet-frost-2": "#f7f0ff",
    "cream-canvas": "#f7f7f5",
    "cream-snow": "#f7fbff",
    "cream-milk": "#f8f2ec",
    "sky-snow": "#f8fafc",
    "cream-frost": "#f8fbff",
    "orange": "#f97316",
    "gold-peach": "#f9d7af",
    "yellow": "#facc15",
    "rose-soft": "#fb7185",
    "orange-soft": "#fb923c",
    "cream-soft": "#fbf7f1",
    "cream-almond": "#fbf7f2",
    "cream-paper": "#fbfbfa",
    "cream-snow-soft": "#fbfdff",
    "amber-soft": "#fcd34d",
    "cream-cloud": "#fcfcfc",
    "cream-porcelain": "#fcfdff",
    "orange-soft-2": "#fdba74",
    "coral-bright": "#ff645f",
    "coral-deep": "#ff6a1a",
    "coral-flame": "#ff6a63",
    "coral-ember": "#ff7a6b",
    "coral-rose": "#ff7b57",
    "coral-soft-2": "#ff7f78",
    "rose": "#ff8a98",
    "coral-pale": "#ff8c73",
    "coral-melon": "#ff8e58",
    "coral": "#ff8e6c",
    "coral-soft": "#ff8f6d",
    "coral-blush": "#ff8f82",
    "coral-soft-3": "#ff9b89",
    "coral-peach-soft": "#ffb39f",
    "coral-peach": "#ffbe79",
    "gold-cream": "#ffd177",
    "gold-soft": "#ffd98d",
    "gold-blush-soft": "#ffe2c7",
    "gold-blush": "#ffe4ca",
    "gold-melon": "#fff0e6",
    "gold-mist": "#fff1b8",
    "gold-ivory-soft": "#fff1ea",
    "gold-ivory": "#fff2df",
    "gold-shell": "#fff2e6",
    "gold-haze": "#fff4d2",
    "gold-shell-deep": "#fff4e7",
    "gold-custard": "#fff6d9",
    "gold-sun": "#fff7cf",
    "gold-light": "#fff7dc",
    "cream-tint": "#fff7ef",
    "gold-haze-2": "#fff9ea",
    "gold-mist-2": "#fffdf0",
    "cream-haze": "#fffdf1",
    "cream": "#fffdfa",
    "white": "#ffffff",
        },
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "pulse-glow": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "pulse-glow": "pulse-glow 2s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
