export const PMGC_2025_RANKINGS = [
  {
    title: "Grand Finals Elimination Rankings",
    columns: [
      { key: "elimins", label: "Elims" },
      { key: "avg_dmg", label: "Avg. Dmg. Dealt" },
      { key: "assists", label: "Assists" },
      { key: "knocks", label: "Knocks" },
      { key: "kd", label: "K/D" },
    ],
    entries: [
      { placement: 1, player: "TOP", country: "Mongolia", team: "Alpha Gaming", elimins: 32, avg_dmg: 461, assists: 24, knocks: 35, kd: 1.78 },
      { placement: 2, player: "Rosemary", country: "Indonesia", team: "Alter Ego Ares", elimins: 32, avg_dmg: 403, assists: 6, knocks: 31, kd: 1.78 },
      { placement: 3, player: "Nolbu", country: "South Korea", team: "Dplus", elimins: 32, avg_dmg: 374, assists: 14, knocks: 31, kd: 1.78 },
      { placement: 4, player: "3More", country: "Saudi Arabia", team: "R8 Esports", elimins: 32, avg_dmg: 322, assists: 11, knocks: 31, kd: 1.78 },
      { placement: 5, player: "Loxy", country: "Turkey", team: "Regnum Carya Esports", elimins: 31, avg_dmg: 366, assists: 16, knocks: 28, kd: 1.72 },
      { placement: 6, player: "Ajay", country: "China", team: "ThunderTalk Gaming", elimins: 29, avg_dmg: 298, assists: 12, knocks: 26, kd: 1.61 },
      { placement: 7, player: "REFUS", country: "Mongolia", team: "Alpha Gaming", elimins: 26, avg_dmg: 380, assists: 19, knocks: 30, kd: 1.44 },
      { placement: 8, player: "PUSHER", country: "Armenia", team: "MadBulls", elimins: 26, avg_dmg: 310, assists: 11, knocks: 24, kd: 1.44 },
      { placement: 9, player: "Marso", country: "Turkey", team: "Kara Esports", elimins: 24, avg_dmg: 351, assists: 11, knocks: 21, kd: 1.33 },
      { placement: 10, player: "OSAL", country: "South Korea", team: "Dplus", elimins: 24, avg_dmg: 214, assists: 12, knocks: 15, kd: 1.33 },
      { placement: 11, player: "Revo", country: "Brazil", team: "Alpha7 Esports", elimins: 23, avg_dmg: 330, assists: 11, knocks: 32, kd: 1.28 },
      { placement: 12, player: "DOK", country: "Mongolia", team: "Alpha Gaming", elimins: 22, avg_dmg: 317, assists: 17, knocks: 25, kd: 1.22 },
      { placement: 13, player: "Xing", country: "China", team: "ThunderTalk Gaming", elimins: 22, avg_dmg: 280, assists: 17, knocks: 22, kd: 1.22 },
      { placement: 14, player: "CEOLATER", country: "Turkey", team: "Kara Esports", elimins: 22, avg_dmg: 241, assists: 7, knocks: 20, kd: 1.22 },
      { placement: 15, player: "TernyK", country: "Thailand", team: "eArena", elimins: 21, avg_dmg: 275, assists: 10, knocks: 26, kd: 1.17 },
      { placement: 16, player: "TW1X", country: "Ukraine", team: "GOAT Team", elimins: 21, avg_dmg: 239, assists: 12, knocks: 20, kd: 1.17 },
      { placement: 17, player: "Obscure", country: "Brazil", team: "Alpha7 Esports", elimins: 21, avg_dmg: 236, assists: 5, knocks: 20, kd: 1.24 },
      { placement: 18, player: "Eren7", country: "Turkey", team: "ULF Esports", elimins: 20, avg_dmg: 307, assists: 9, knocks: 17, kd: 1.11 },
      { placement: 19, player: "Cyxae", country: "South Korea", team: "DRX", elimins: 20, avg_dmg: 287, assists: 9, knocks: 20, kd: 1.11 },
      { placement: 20, player: "KillerJoe", country: "Ukraine", team: "GOAT Team", elimins: 20, avg_dmg: 282, assists: 12, knocks: 20, kd: 1.11 },
      { placement: 21, player: "Wild", country: "Turkey", team: "Regnum Carya Esports", elimins: 20, avg_dmg: 260, assists: 16, knocks: 21, kd: 1.11 },
      { placement: 22, player: "Zyol", country: "Mongolia", team: "Alpha Gaming", elimins: 20, avg_dmg: 219, assists: 14, knocks: 22, kd: 1.11 },
      { placement: 23, player: "Kecth", country: "Turkey", team: "ULF Esports", elimins: 20, avg_dmg: 206, assists: 7, knocks: 21, kd: 1.11 },
      { placement: 24, player: "HYUNBIN", country: "South Korea", team: "DRX", elimins: 18, avg_dmg: 274, assists: 16, knocks: 20, kd: 1.00 },
      { placement: 25, player: "ParaJin", country: "Vietnam", team: "D'Xavier", elimins: 18, avg_dmg: 215, assists: 8, knocks: 17, kd: 1.00 },
      { placement: 26, player: "Guizão", country: "Brazil", team: "Alpha7 Esports", elimins: 18, avg_dmg: 204, assists: 9, knocks: 21, kd: 1.00 },
      { placement: 27, player: "SiTing", country: "China", team: "ThunderTalk Gaming", elimins: 18, avg_dmg: 190, assists: 9, knocks: 15, kd: 1.00 },
      { placement: 28, player: "SOEZ", country: "South Korea", team: "DRX", elimins: 18, avg_dmg: 157, assists: 7, knocks: 14, kd: 1.00 },
      { placement: 29, player: "KRAKKEN", country: "Russia", team: "GOAT Team", elimins: 17, avg_dmg: 252, assists: 7, knocks: 23, kd: 0.94 },
      { placement: 30, player: "Soulless", country: "Turkey", team: "ULF Esports", elimins: 17, avg_dmg: 229, assists: 7, knocks: 20, kd: 0.94 },
      { placement: 31, player: "Marth", country: "Saudi Arabia", team: "R8 Esports", elimins: 17, avg_dmg: 224, assists: 16, knocks: 12, kd: 0.94 },
      { placement: 32, player: "Zwolf", country: "Turkey", team: "Regnum Carya Esports", elimins: 17, avg_dmg: 205, assists: 9, knocks: 16, kd: 0.94 },
      { placement: 33, player: "Scarface", country: "Turkey", team: "ULF Esports", elimins: 16, avg_dmg: 287, assists: 18, knocks: 15, kd: 0.89 },
      { placement: 34, player: "FLIP", country: "Ukraine", team: "MadBulls", elimins: 16, avg_dmg: 208, assists: 9, knocks: 13, kd: 0.89 },
      { placement: 35, player: "NadeTii", country: "Vietnam", team: "D'Xavier", elimins: 16, avg_dmg: 162, assists: 10, knocks: 11, kd: 0.89 },
      { placement: 36, player: "2ed3ull", country: "Thailand", team: "Vampire Esports", elimins: 15, avg_dmg: 277, assists: 7, knocks: 20, kd: 0.94 },
      { placement: 37, player: "iD7", country: "Saudi Arabia", team: "R8 Esports", elimins: 15, avg_dmg: 261, assists: 11, knocks: 16, kd: 0.94 },
      { placement: 38, player: "Jowker", country: "Thailand", team: "eArena", elimins: 15, avg_dmg: 240, assists: 14, knocks: 13, kd: 0.83 },
      { placement: 39, player: "TonyK", country: "Thailand", team: "Vampire Esports", elimins: 15, avg_dmg: 199, assists: 6, knocks: 14, kd: 1.00 },
      { placement: 40, player: "V1C", country: "Russia", team: "GOAT Team", elimins: 15, avg_dmg: 193, assists: 13, knocks: 13, kd: 0.83 },
      { placement: 41, player: "Bowz", country: "Vietnam", team: "Team Flash", elimins: 14, avg_dmg: 251, assists: 12, knocks: 16, kd: 0.78 },
      { placement: 42, player: "Zhius", country: "Vietnam", team: "Team Flash", elimins: 14, avg_dmg: 249, assists: 6, knocks: 19, kd: 0.78 },
      { placement: 43, player: "King", country: "Taiwan", team: "ThunderTalk Gaming", elimins: 14, avg_dmg: 222, assists: 9, knocks: 18, kd: 0.78 },
      { placement: 44, player: "Carrilho", country: "Brazil", team: "Alpha7 Esports", elimins: 14, avg_dmg: 196, assists: 19, knocks: 18, kd: 0.78 },
      { placement: 45, player: "Qx", country: "South Korea", team: "DRX", elimins: 14, avg_dmg: 180, assists: 8, knocks: 15, kd: 0.78 },
      { placement: 46, player: "Topz", country: "Vietnam", team: "Team Flash", elimins: 14, avg_dmg: 178, assists: 13, knocks: 14, kd: 0.78 },
      { placement: 47, player: "Win", country: "Vietnam", team: "Team Flash", elimins: 13, avg_dmg: 200, assists: 13, knocks: 16, kd: 0.72 },
      { placement: 48, player: "Lewis", country: "Turkey", team: "Kara Esports", elimins: 13, avg_dmg: 187, assists: 16, knocks: 17, kd: 0.72 },
      { placement: 49, player: "TULIKA", country: "Ukraine", team: "MadBulls", elimins: 13, avg_dmg: 185, assists: 11, knocks: 15, kd: 0.72 },
      { placement: 50, player: "lazarus", country: "Thailand", team: "Vampire Esports", elimins: 12, avg_dmg: 236, assists: 12, knocks: 17, kd: 0.67 },
      { placement: 51, player: "LEMON", country: "Ukraine", team: "MadBulls", elimins: 12, avg_dmg: 214, assists: 9, knocks: 19, kd: 0.67 },
      { placement: 52, player: "PrEStlGe", country: "Saudi Arabia", team: "R8 Esports", elimins: 12, avg_dmg: 164, assists: 11, knocks: 14, kd: 0.67 },
      { placement: 53, player: "Alva", country: "Indonesia", team: "Alter Ego Ares", elimins: 12, avg_dmg: 146, assists: 4, knocks: 11, kd: 0.86 },
      { placement: 54, player: "LeVis", country: "Vietnam", team: "D'Xavier", elimins: 11, avg_dmg: 222, assists: 11, knocks: 16, kd: 0.61 },
      { placement: 55, player: "Krypton", country: "Indonesia", team: "Alter Ego Ares", elimins: 11, avg_dmg: 179, assists: 8, knocks: 16, kd: 0.61 },
      { placement: 56, player: "MEOWLA", country: "Thailand", team: "Vampire Esports", elimins: 11, avg_dmg: 177, assists: 6, knocks: 12, kd: 0.73 },
      { placement: 57, player: "Nc2", country: "Thailand", team: "eArena", elimins: 11, avg_dmg: 174, assists: 6, knocks: 13, kd: 0.85 },
      { placement: 58, player: "FAVIAN", country: "South Korea", team: "Dplus", elimins: 10, avg_dmg: 166, assists: 13, knocks: 13, kd: 0.56 },
      { placement: 59, player: "Lamborghini", country: "Vietnam", team: "D'Xavier", elimins: 10, avg_dmg: 89, assists: 3, knocks: 6, kd: 0.56 },
      { placement: 60, player: "chpz", country: "South Korea", team: "Dplus", elimins: 9, avg_dmg: 244, assists: 15, knocks: 13, kd: 0.50 },
      { placement: 61, player: "MORMAN", country: "Thailand", team: "eArena", elimins: 9, avg_dmg: 194, assists: 7, knocks: 9, kd: 0.60 },
      { placement: 62, player: "Moana", country: "Indonesia", team: "Alter Ego Ares", elimins: 9, avg_dmg: 163, assists: 6, knocks: 4, kd: 0.75 },
      { placement: 63, player: "Sylas", country: "Turkey", team: "Regnum Carya Esports", elimins: 9, avg_dmg: 152, assists: 11, knocks: 9, kd: 0.50 },
      { placement: 64, player: "Poser", country: "Turkey", team: "Kara Esports", elimins: 6, avg_dmg: 123, assists: 5, knocks: 10, kd: 0.33 },
      { placement: 65, player: "SAKURA", country: "Thailand", team: "eArena", elimins: 5, avg_dmg: 203, assists: 1, knocks: 8, kd: 0.63 },
      { placement: 66, player: "Snape", country: "Indonesia", team: "Alter Ego Ares", elimins: 4, avg_dmg: 137, assists: 3, knocks: 6, kd: 0.40 },
      { placement: 67, player: "Gewwy", country: "Thailand", team: "Vampire Esports", elimins: 3, avg_dmg: 90, assists: 2, knocks: 3, kd: 0.38 },
      { placement: 68, player: "Mafioso", country: "Brazil", team: "Alpha7 Esports", elimins: 0, avg_dmg: 322, assists: 2, knocks: 1, kd: 0.00 },
      { placement: 69, player: "Damar", country: "Saudi Arabia", team: "R8 Esports", elimins: 0, avg_dmg: 38, assists: 0, knocks: 0, kd: 0.00 },
    ],
  },
];
