export const DEFAULT_CUSTOM_CONFIG = {
  title: "Match Results", tag: "LIVE", subtitle: "Grand Finals",
  playerName: "", teamName: "", bodyText: "",
  tournamentName: "", tournamentLogoUrl: "",
  stats: [], standingsRows: [],
  accent: "var(--brand-orange)", bgColor: "var(--brand-white)", cardBg: "var(--brand-sky-snow)", cardBorder: "var(--art-e2e8f0)",
  titleColor: "var(--brand-ink-slate)", titleSize: "32px", titleWeight: "900", muted: "var(--brand-slate-400)",
  bodyColor: "var(--art-334155)", bodySize: "11px", bodyWeight: "600",
  statsCols: 4, colHeaders: "Matches,Placements,Finishes,Total",
  colFields: "matches,placement,finishes,points", topN: 0,
  leftLabel: "", leftBg: "var(--art-16a34a)", leftColor: "var(--brand-white)",
  rightLabel: "", rightBg: "var(--art-7c3aed)", rightColor: "var(--brand-white)",
  socialLinks: [],
  showHeader: true, showTag: true, showTitle: true, showPlayer: true,
  showStats: true, showTable: true, showBody: true, showFooter: true,
  showSocial: true, showBgArt: false, bgArtText: "",
  padding: "16px 20px", accentBarHeight: "4px",
  playerPhoto: "", teamLogo: "",
  brandLogo: "", brandText: "",
};
