export const DEFAULT_CUSTOM_CONFIG = {
  title: "Match Results", tag: "LIVE", subtitle: "Grand Finals",
  playerName: "", teamName: "", bodyText: "",
  tournamentName: "", tournamentLogoUrl: "",
  stats: [], standingsRows: [],
  accent: "#f97316", bgColor: "#ffffff", cardBg: "#f8fafc", cardBorder: "#e2e8f0",
  titleColor: "#0f172a", titleSize: "32px", titleWeight: "900", muted: "#94a3b8",
  bodyColor: "#334155", bodySize: "11px", bodyWeight: "600",
  statsCols: 4, colHeaders: "Matches,Placements,Finishes,Total",
  colFields: "matches,placement,finishes,points", topN: 0,
  leftLabel: "", leftBg: "#16a34a", leftColor: "#ffffff",
  rightLabel: "", rightBg: "#7c3aed", rightColor: "#ffffff",
  socialLinks: [],
  showHeader: true, showTag: true, showTitle: true, showPlayer: true,
  showStats: true, showTable: true, showBody: true, showFooter: true,
  showSocial: true, showBgArt: false, bgArtText: "",
  padding: "16px 20px", accentBarHeight: "4px",
  playerPhoto: "", teamLogo: "",
  brandLogo: "", brandText: "",
};
