export const normalizeLookupValue = (value) =>
  String(value || "")
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "");

export const TEAM_ALIAS_KEY_MAP = {
  godlike: "godlikeesports",
  godlikeesports: "godlikeesports",
  heroxtremegodlike: "godlikeesports",
  heroxtremegodlikeesports: "godlikeesports",
  godsreign: "godsreign",
  gladiatorsesports: "gladiatorsesports",
  gdr: "gladiatorsesports",
  gods: "godsreign",
  "8bitxcsesports": "8bit",
  "8bit": "8bit",
  aryanxtmggaming: "teamaryan",
  teamax: "teamaryan",
  teamaryan: "teamaryan",
  nsredforce: "nongshimredforce",
  nongshimredforce: "nongshimredforce",
  nongshimredforceesports: "nongshimredforce",
  thwxnonxesports: "nonxesports",
  nonxesports: "nonxesports",
  teamxspark: "revenantxspark",
  tx: "revenantxspark",
  revenantesports: "revenantxspark",
  revenantxspark: "revenantxspark",
  rnt: "revenantxspark",
  orangutan: "orangutan",
  soul: "teamsoul",
  teamsoul: "teamsoul",
  iqoosoul: "teamsoul",
  iqooreckoningesports: "reckoningesports",
  reckoningesports: "reckoningesports",
  iqoorevenantxspark: "revenantxspark",
  iqoo8bit: "8bit",
  iqooorangutan: "orangutan",
  truerippersxinfinix: "truerippers",
  infinixtruerippers: "truerippers",
  truerippers: "truerippers",
  dpluskia: "dplus",
  dplus: "dplus",
  mysterious4esports: "mysterious4",
  mysterious4: "mysterious4",
  madkings: "madkingsesports",
  madkingsesports: "madkingsesports",
  blind: "blindesports",
  blindesports: "blindesports",
  bb: "bigbrotheresports",
  bigbrotheresports: "bigbrotheresports",
  mdl: "medalesports",
  medalesports: "medalesports",
  me: "midwaveesports",
  midwaveesports: "midwaveesports",
  or: "oresports",
  oresports: "oresports",
  gxr: "glitchxreborn",
  glitchxreborn: "glitchxreborn",
  mici: "miciesports",
  miciesports: "miciesports",
  gs: "growingstrong",
  growingstrong: "growingstrong",
  "4am": "4aggressiveman",
  "4aggressiveman": "4aggressiveman",
  no: "nightowls",
  nightowls: "nightowls",
  ge: "globalesports",
  globalesports: "globalesports",
  rge: "reckoningesports",
  fs: "fsesports",
  fsesports: "fsesports",
  tt: "teamtamilas",
  teamaaru: "teamaaru",
  aaru: "teamaaru",
  vst: "vasistaesports",
  vasistaesports: "vasistaesports",
  mogo: "mogoesports",
  mogoesports: "mogoesports",
  cg: "carnivalgaming",
  carnivalgaming: "carnivalgaming",
  inferno: "infernosquad",
  entity: "entitygaming",
  entitygaming: "entitygaming",
  numen: "numenesports",
  numenesports: "numenesports",
  hydra: "hydra",
  tte: "teamtogetheresports",
  teamtogetheresports: "teamtogetheresports",
  auto: "autobotzesports",
  autobotzesports: "autobotzesports",
  psyche: "teampsyche",
  teampsyche: "teampsyche",
  troytamilanesports: "troytamilianesports",
  troytamilans: "troytamilianesports",
  troytamilansesports: "troytamilianesports",
  troytamilianesports: "troytamilianesports",
  k9esports: "k9esports",
  cincinnatikids: "cincinnatikids",
  infernosquad: "risingesports",
  hailinfernosquad: "risingesports",
  risingesports: "risingesports",
  rse: "risingesports",
  rie: "risingesports",
  versatileesports: "teamversatile",
  teamversatile: "teamversatile",
  "4everxredxross": "teamredxross",
  redxross: "teamredxross",
  teamredxross: "teamredxross",
  teaminsaneesports: "teaminsane",
  teaminsane: "teaminsane",
  loshermanos: "loshermanosesports",
  loshermanosesports: "loshermanosesports",
  learnfrompast: "learnfrompast",
  hadesh4k: "teamh4k",
  teamtamilas: "teamtamilas",
  teamtamillas: "teamtamilas",
  godscentesports: "godsentesports",
  godsentesports: "godsentesports",
  godsentlegions: "godsentlegions",
  apexgaming: "teamapexgaming",
  teamapexgaming: "teamapexgaming",
  teamvanguard: "teamvanguard",
  t7xorionesports: "t7xorionesports",
  genxfmesports: "genxfmesports",
  genxfm: "genxfmesports",
  likithaesports: "likithaesports",
  rapidchaosesports: "rapidchaosesports",
  higgboson: "higgbosonesports",
  higgbosonesports: "higgbosonesports",
  esportsocial: "esportsocial",
  esportssocial: "esportsocial",
  quantumsparks: "quantumsparks",
  jaapiesports: "jaapiesports",
  teamdoxy: "teamdoxy",
  someonesdream: "someonesdream",
  zeroarkofficial: "zeroarkofficial",
  santaesp: "santaesports",
  santaesports: "santaesports",
  thundergodsxtortugagaming: "thundergodsxtortugagaming",
  thundergodstortugagaming: "thundergodsxtortugagaming",
  thundergodsesports: "thundergodsxtortugagaming",
  divinegaming: "divinegaming",
  blinkesports: "blinkesports",
  jaguaresports: "jaguaresports",
  windgodesports: "windgodesports",
  naqshesports: "naqshesports",
  m4xnaqshesports: "naqshesports",
  riotnationz: "riotnationz",
  riotnations: "riotnationz",
  hadxesports: "hadxesports",
  hadx: "hadxesports",
  lastadeesports: "lastadeesports",
  sevengodsesports: "7godsesports",
  "7godsesports": "7godsesports",
  auraxesports: "auraxesports",
  auraxesport: "auraxesports",
  aresesport: "aresesport",
  aresesports: "aresesport",
  oopsofficial: "oopsofficial",
};

export const TEAM_ALIAS_VARIANTS = Object.entries(TEAM_ALIAS_KEY_MAP).reduce(
  (acc, [alias, canonical]) => {
    const list = acc.get(canonical) || new Set();
    list.add(alias);
    acc.set(canonical, list);
    return acc;
  },
  new Map(),
);

export const canonicalizeTeamLookupValue = (value) => {
  const compact = normalizeLookupValue(value);
  if (!compact) return "";
  const withoutSponsors = compact.replace(
    /^(iqoo|oneplus|heroxtreme|infinix)+/g,
    "",
  );
  return TEAM_ALIAS_KEY_MAP[withoutSponsors] || withoutSponsors;
};
